name: Build APK Assinado

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give permission to wrapper
        run: chmod +x gradlew

      - name: Build using wrapper
        run: ./gradlew clean assembleDebug --no-daemon

      - name: Assinar APK
        run: |
          # 1. Localiza as ferramentas do Android
          BUILD_TOOLS=$(ls -d $ANDROID_HOME/build-tools/* | tail -1)
          
          # 2. Alinha e Assina lendo a chave diretamente do repositório!
          $BUILD_TOOLS/zipalign -v -p 4 app/build/outputs/apk/debug/app-debug.apk app-alinhado.apk
          $BUILD_TOOLS/apksigner sign --ks minha-chave.jks --ks-key-alias "meu-app" --ks-pass "pass:15349276" --key-pass "pass:15349276" --out app-final-assinado.apk app-alinhado.apk

      - name: Upload APK Assinado
        uses: actions/upload-artifact@v4
        with:
          name: app-final-assinado
          path: app-final-assinado.apk
