name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite rodar o build manualmente no GitHub!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give permission to wrapper
        run: chmod +x gradlew

      # Modificado para gerar a versão Release em vez de Debug
      - name: Build using wrapper (Release)
        run: ./gradlew clean assembleRelease --no-daemon

      # Novo passo que usa seus Segredos para assinar o arquivo
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      # Modificado para pegar apenas o arquivo que já foi assinado
      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-assinado
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
