name: Build APK Garantido

on:
  workflow_dispatch: # Botão manual de rodar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gerar App (Sem Frescuras)
        run: |
          chmod +x gradlew
          ./gradlew clean assembleDebug --no-daemon

      - name: Entregar App
        uses: actions/upload-artifact@v4
        with:
          name: meu-app-pronto
          path: app/build/outputs/apk/debug/app-debug.apk
